name: Codacy Coverage Reporter

on: [push, pull_request]

jobs:
  codacy-coverage-reporter:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake lcov
      
      - name: Configure CMake
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
      
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
      
      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C Debug --output-on-failure
      
      - name: Generate coverage report
        if: always()
        working-directory: ${{github.workspace}}/build
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
      
      - name: List files
        working-directory: ${{github.workspace}}/build
        run: |
          ls -R
          find . -name "*.gcda" -o -name "*.gcno"
      
      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        if: always()
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: build/coverage.info
